const { test, expect } = require('@playwright/test')
const assert = require('assert')
const exp = require('constants')
test('Verify the dropdown functionality',async({page})=>{
    await page.goto('https://webdriveruniversity.com/Dropdown-Checkboxes-RadioButtons/index.html')
    await page.selectOption('#dropdowm-menu-1','Python')
    const ActualValue = await page.$eval('#dropdowm-menu-1',(el)=> el.value)
    assert.strictEqual(ActualValue,'python')
    await page.selectOption('#dropdowm-menu-2','Maven')
    const ActualValue2 = await page.$eval('#dropdowm-menu-2',(el)=> el.value)
    assert.strictEqual(ActualValue2,'maven')
    // const text = await page.$eval('h1',(el)=> el.textContent())
    // assert.strictEqual(text,'Dropdown Menu(s), Checkboxe(s) & Radio Button(s)')
    let textContentVal= await page.$eval('h1',(el)=>el.textContent)
    assert.strictEqual(textContentVal,"Dropdown Menu(s), Checkboxe(s) & Radio Button(s)")
    let text2 =await page.locator('h1').textContent()
    console.log(text2)
})

test('Verify checkBox functionality in playwright',async({page})=>{
    await page.goto('https://webdriveruniversity.com/Dropdown-Checkboxes-RadioButtons/index.html')
    await page.check('input[value="option-2"]')
    await page.uncheck('input[value="option-3"]')
    const check1 = await page.$eval('input[value="option-2"]',(el)=>el.checked)
    assert.strictEqual(check1,true)
    const check2 = await page.$eval('input[value="option-3"]',(el)=>el.checked)
    assert.strictEqual(check2,false)
    expect(await page.locator('input[value="option-4"]')).not.toBeChecked()
    await page.locator('input[value="option-4"]').check()
    expect(page.locator('input[value="option-4"]')).toBeChecked()
})

test.only('Verify Radio buttons functionality in playwright',async({page})=>{
    await page.goto('https://webdriveruniversity.com/Dropdown-Checkboxes-RadioButtons/index.html')
    await page.check('[value="green"]')
    let radio = await page.$eval('[value="green"]',(el)=>el.checked)
    assert.strictEqual(radio,true)
    await page.locator('[value="purple"]').check()
    await expect(page.locator('[value="purple"]')).toBeChecked()
    let radio2 = await page.$eval('[value="yellow"]',(el) => el.checked)
    assert.strictEqual(radio2,false)
    await expect(page.locator('[value="yellow"]')).not.toBeChecked()
})